services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: spartan
      POSTGRES_PASSWORD: spartan
      POSTGRES_DB: spartan_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
